name: Generate Animation

on:
  schedule: # execute every 24 hours
    - cron: "0 */24 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    timeout-minutes: 5

    permissions: 
      contents: write

    runs-on: ubuntu-latest

    steps:
      # Snake Animation
      - name: update snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=gray&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
